### ISSUE TITLE
Added Korean localization

### ISSUE THREAD

**Issue by danbom** [imi-muenster/OpenEDC#2]
Hello,

we are developers(@danbom, @ssso-pro1) who work for a CRO company called C&R Research in South Korea.
We made an issue because we've updated a translation script and found some supplements to improve.

Our company has a lot of interest in OpenEDC, so we are studying about your service.
If you guys don't mind, we are hoping to work on various related tasks in the future
and keep on track of your service to stay updated.
For example, we are planning to add dark mode and other designs.

For this time,
1. We added a Korean translation script for internationalization.
2. We found some supplements, which we'll leave on a new issue.

We would be looking forward for you reply.
Thanks 😁

**Comment by imi-muenster** [comment]
Hi you two,

as already communicated via email: thank you both very much for the pull request. If there are other areas for improvements that you identify, feel free to open any other issue or pull request.

Best,
Leo
